#! /bin/bash
#
# Run dtiinit-demo
#

CONTAINER="[scitran/dwi-split-shells]"

# Built to flywheel-v0 spec.
FLYWHEEL_BASE=/flywheel/v0
MCR_ROOT=/opt/mcr/v93/

# Make sure that /output directory is empty (all content will be removed later).
OUTPUT_DIR=$FLYWHEEL_BASE/output

echo -e "$CONTAINER  Initiated"

if [[ ! -d "$OUTPUT_DIR" ]]
    then
        echo "$CONTAINER  $OUTPUT_DIR not found!"
        exit 1
fi

bvecFile=$(find $FLYWHEEL_BASE/input/bvec/ -type f -name "*.bvec*")
bvalFile=$(find $FLYWHEEL_BASE/input/bval/ -type f -name "*.bval*")
dwiFile=$(find $FLYWHEEL_BASE/input/dwi/ -type f -name "*.nii*")


# Run the Matlab executable 
/msa/run_shellsplit.sh "$MCR_ROOT" "$bvecFile" "$bvalFile" "$dwiFile" "$OUTPUT_DIR"



# Get a list of the files in the output directory
outputs=$(find $OUTPUT_DIR/* -maxdepth 0 -type f)


# If outputs exist, generate metadata, and exit
if [[ -z $outputs ]]
    then
        echo "$CONTAINER  No results found in output directory... Exiting"
        exit 1
    else
        cd $OUTPUT_DIR
        echo -e "$CONTAINER  Wrote: `ls`"
        echo -e "$CONTAINER  Done!"
fi



chmod -R 777 $OUTPUT_DIR


exit 0



